version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  metabase:
    image: metabase/metabase:v0.49.13
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data

  airflow:
    image: custom-airflow:2.8.3
    container_name: airflow
    restart: always
    depends_on:
      - clickhouse
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: 'your_fernet_key'
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: 'sqlite:////usr/local/airflow/airflow.db'
      _PIP_ADDITIONAL_REQUIREMENTS: 
    volumes:
      - ./deploy/dags:/opt/airflow/dags
      - ./deploy/dbt:/opt/airflow/dbt
      - ./deploy/logs:/opt/airflow/logs

volumes:
  clickhouse_data:
  metabase_data:
  airflow_logs: