version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_init:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  metabase:
    image: metabase-with-clickhouse:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data

  airflow:
    image: custom-airflow:2.8.3
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://airflow:airflow@postgres/airflow'
      _PIP_ADDITIONAL_REQUIREMENTS: 
    ports:
      - "8080:8080"
    volumes:
      - ./deploy/dags:/opt/airflow/dags
      - ./deploy/dbt:/opt/airflow/dbt
      - ./deploy/logs:/opt/airflow/logs
    depends_on:
      - postgres
    command: standalone
    
  postgres:
    image: postgres:13
    container_name: postgres-airflow
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  clickhouse_data:
  postgres_data:
  metabase_data:
  airflow_logs: