name: 'analytics'
version: '0.1'
profile: 'airflow'
config-version: 2

model-paths: [ "models" ]
analysis-paths: [ "analysis" ]
test-paths: [ "tests" ]
seed-paths: [ "sample" ]
macro-paths: [ "macros" ]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  analytics:
    +materialized: table

    staging:
      +schema: stage
      +tags: 'stage'

    core:
      +schema: core
      +tags: 'core'

    marts:
      +schema: marts
      +tags: 'marts'