version: 2
models:
- name: daily_sales_summary
  description: Модель для расчета общей суммы продаж по дням.
  columns:
  - name: order_date
    description: Дата заказа.
    tests:
    - not_null
  - name: daily_total_sales
    description: Сумма продаж за день.
    tests:
    - not_null
- name: unique_customers_by_region
  description: Модель для расчета количества уникальных покупателей по регионам.
  columns:
  - name: region_id
    description: Идентификатор региона.
    tests:
    - not_null
  - name: unique_customers_count
    description: Количество уникальных покупателей в регионе.
    tests:
    - not_null
- name: average_order_amount
  description: Модель для расчета среднего чека.
  columns:
  - name: customer_id
    description: Идентификатор клиента.
    tests:
    - not_null
  - name: avg_order_amount
    description: Средняя сумма заказа клиента.
    tests:
    - not_null
