version: 2
models:
- name: sales_summary
  description: Aggregated sales data including total sales and sales per region.
  columns:
  - name: order_id
    description: Unique identifier for the order
    tests:
    - unique
    - not_null
  - name: product_id
    description: Identifier of the product
    tests:
    - not_null
  - name: timestamp
    description: Timestamp of the order
    tests:
    - not_null
  - name: customer_id
    description: Identifier of the customer
    tests:
    - not_null
  - name: money
    description: Amount of money spent
    tests:
    - not_null
  - name: region_id
    description: Region identifier of the customer
    tests:
    - not_null
  - name: registration_date
    description: Registration date of the customer
    tests:
    - not_null
  - name: total_sales
    description: Total sales amount for the day
    tests:
    - not_null
  - name: total_sales_per_region
    description: Total sales amount per region
    tests:
    - not_null
- name: customer_lifetime_value
  description: Calculates the lifetime value of each customer.
  columns:
  - name: customer_id
    description: Identifier of the customer
    tests:
    - unique
    - not_null
  - name: lifetime_value
    description: Total amount spent by the customer
    tests:
    - not_null
- name: average_order_value
  description: Calculates the average order value for each order.
  columns:
  - name: order_id
    description: Unique identifier for the order
    tests:
    - unique
    - not_null
  - name: average_order_value
    description: Average value of the order
    tests:
    - not_null
