version: 2
models:
- name: stg_openmeteo_api
  description: Stage model for OpenMeteo API weather data in Moscow.
  columns:
  - name: temperature
    description: Temperature in degrees Celsius.
    tests:
    - not_null
    - numeric
  - name: humidity
    description: Humidity percentage.
    tests:
    - not_null
    - numeric
  - name: wind_speed
    description: Wind speed in meters per second.
    tests:
    - not_null
    - numeric
  - name: precipitation
    description: Precipitation level in millimeters.
    tests:
    - not_null
    - numeric
  - name: extracted_at
    description: Timestamp indicating when the data was staged.
    tests:
    - not_null
  meta:
    source: OpenMeteo API
    layer: stage
    tags:
    - weather_data
    - moscow
