version: 2
models:
- name: sales_by_day
  description: Aggregated sales data by day
  columns:
  - name: date
    description: Date of the sales
    tests:
    - not_null
  - name: total_sales
    description: Total sales amount for the day
    tests:
    - not_null
- name: unique_customers_by_region
  description: Count of unique customers by region
  columns:
  - name: region_id
    description: Region identifier
    tests:
    - not_null
  - name: unique_customers
    description: Number of unique customers in the region
    tests:
    - not_null
- name: average_order_value
  description: Average value of orders
  columns:
  - name: average_order_value
    description: Average order value
    tests:
    - not_null
- name: customer_order_summary
  description: Summary of customer orders including total orders, total spent, and
    average order value
  columns:
  - name: customer_id
    description: Unique identifier for the customer
    tests:
    - not_null
    - unique
  - name: total_orders
    description: Total number of orders made by the customer
    tests:
    - not_null
  - name: total_spent
    description: Total amount spent by the customer
    tests:
    - not_null
  - name: average_order_value
    description: Average value of orders made by the customer
    tests:
    - not_null
