version: 2
models:
- name: int_orders_summary
  description: Модель для агрегирования данных о заказах по клиентам.
  columns:
  - name: customer_id
    description: Идентификатор клиента.
    tests:
    - not_null
  - name: total_orders
    description: Общее количество заказов клиента.
    tests:
    - not_null
  - name: total_amount
    description: Общая сумма заказов клиента.
    tests:
    - not_null
  - name: first_order_date
    description: Дата первого заказа клиента.
    tests:
    - not_null
  - name: last_order_date
    description: Дата последнего заказа клиента.
    tests:
    - not_null
- name: int_customers_enriched
  description: Модель для объединения данных о клиентах с агрегированными данными
    о заказах.
  columns:
  - name: customer_id
    description: Идентификатор клиента.
    tests:
    - not_null
    - unique
  - name: name
    description: Имя клиента.
    tests:
    - not_null
  - name: region_id
    description: Идентификатор региона клиента.
    tests:
    - not_null
  - name: age
    description: Возраст клиента.
    tests:
    - not_null
  - name: total_orders
    description: Общее количество заказов клиента.
    tests: []
  - name: total_amount
    description: Общая сумма заказов клиента.
    tests: []
  - name: first_order_date
    description: Дата первого заказа клиента.
    tests: []
  - name: last_order_date
    description: Дата последнего заказа клиента.
    tests: []
