version: 2
models:
- name: stg_orders
  description: Stage layer view for orders
  columns:
  - name: order_id
    description: Unique identifier for the order
    tests:
    - unique
    - not_null
  - name: product_id
    description: Identifier of the product
    tests:
    - not_null
  - name: timestamp
    description: Timestamp of the order
    tests:
    - not_null
  - name: customer_id
    description: Identifier of the customer
    tests:
    - not_null
  - name: money
    description: Amount of money spent
    tests:
    - not_null
  - name: etl_loaded_at
    description: Timestamp when the record was loaded into the stage
    tests:
    - not_null
- name: stg_customers
  description: Stage layer view for customers
  columns:
  - name: region_id
    description: Region identifier of the customer
    tests:
    - not_null
  - name: registration_date
    description: Registration date of the customer
    tests:
    - not_null
  - name: customer_id
    description: Unique identifier for the customer
    tests:
    - unique
    - not_null
  - name: etl_loaded_at
    description: Timestamp when the record was loaded into the stage
    tests:
    - not_null
