version: 2
models:
- name: stg_orders
  description: Stage-модель для таблицы заказов.
  columns:
  - name: order_id
    description: Уникальный идентификатор заказа.
    tests:
    - not_null
    - unique
  - name: product_id
    description: Идентификатор продукта.
    tests:
    - not_null
  - name: customer_id
    description: Идентификатор клиента.
    tests:
    - not_null
  - name: amount
    description: Сумма заказа.
    tests:
    - not_null
  - name: timestamp
    description: Временная метка заказа.
    tests:
    - not_null
  - name: processed_at
    description: Время обработки записи.
    tests: []
- name: stg_customers
  description: Stage-модель для таблицы клиентов.
  columns:
  - name: customer_id
    description: Уникальный идентификатор клиента.
    tests:
    - not_null
    - unique
  - name: name
    description: Имя клиента.
    tests:
    - not_null
  - name: region_id
    description: Идентификатор региона клиента.
    tests:
    - not_null
  - name: age
    description: Возраст клиента.
    tests:
    - not_null
  - name: processed_at
    description: Время обработки записи.
    tests: []
